name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
  pull_request:
    branches:
      - main
      - master

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies (Backend)
        working-directory: ./server
        run: npm install

      - name: Install Dependencies (Frontend)
        working-directory: ./client
        run: npm install

      - name: Run Backend Unit Tests
        working-directory: ./server
        run: npm test

      - name: Run Frontend Unit Tests
        working-directory: ./client
        run: npm test

      - name: Run ESLint (Backend)
        working-directory: ./server
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run ESLint (Frontend)
        working-directory: ./client
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Secret Scanning with CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
