GET http://localhost:3001/api/most-purchased-products
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjQ0ZjU5ZGZmNTgxODBmMDAxZGViOGMiLCJpYXQiOjE3MTczNTQ4MDgsImV4cCI6MTcxNzM1ODQwOH0.aGlUUAivF4xEGrU-9qYJVLxcWJFd8rAo_98hooRubqWg43YE8GLiBRPaJ1ReGzAysA6V1Q_CorfXeDRx11QK_WzFOlbCgS3OqqyQ5V78pO7EBqGgg3_rfRRkxLtNcvec6m3CtkLkdoJAWGLLQBbMFsPQBRlGffdk2-z1CpWIlkXk7TxV_ts54sGeDsL13GZe5pUir3p52JBaAE7rVJkrw0dF9o0Dk8kczS04b5ZCW6jf6xR6DqcQSnP1TXJk6KhFn-A-Z5jRD9xzkpkgnbOLKz7AEX5AEeWAbtq32N-iD1rUCIyaBzw7A8tQs2ZveQN9QIjWeAXV3w2gYC7rjdiPGirJISta5KClCNqq_6znY2tVHnoQD2_jsnviiYsUfUbBcbCWgQYX6X1CIq_a94kfVc7U3DiaE9QGOJ12yttDXwaPwc65tLvYbLHL2ow8Teq-Kf29UdpLtjK75EBUZEehCZWBeWHD1IaRrrlDUa6Ly_hVK99A9zj81Ub01TiZGOad3QQ_NAgaCpV5y31kt13_mWyPar01Gi8KDEEHUzyT1nw4KWpTulK0D2sKLVeGIaKM2JXShebJ9OpD9z-MwsZ03QX96QBSRbEZwhTYu_SP9G_jed9a7N28_uNFpPwLXQe4tpB0qEbaPnlTXw3wx25-JWT118s6p9lgNQ-3Fuolu0M